### ISSUE TITLE
Build breaks: error: failed to run custom build command for `openssl-sys v0.9.80`

### ISSUE THREAD

**Issue by yurivict** [gbj/leptos#211]
Not sure why does it need to rebuild OpenSSL at all.

**Comment by yurivict** [comment]
```
warning: unnecessary parentheses around match arm expression
   --> /usr/ports/www/leptos/work/leptos-0.1.0-alpha/cargo-crates/ring-0.16.20/build.rs:625:21
    |
625 |         "x86_64" => ("win64"),
    |                     ^       ^
    |
    = note: `#[warn(unused_parens)]` on by default
help: remove these parentheses
    |
625 -         "x86_64" => ("win64"),
625 +         "x86_64" => "win64",
    |

warning: unnecessary parentheses around match arm expression
   --> /usr/ports/www/leptos/work/leptos-0.1.0-alpha/cargo-crates/ring-0.16.20/build.rs:626:18
    |
626 |         "x86" => ("win32"),
    |                  ^       ^
    |
help: remove these parentheses
    |
626 -         "x86" => ("win32"),
626 +         "x86" => "win32",
    |

warning: `ring` (build script) generated 2 warnings
   Compiling openssl-sys v0.9.80
     Running `/usr/ports/www/leptos/work/target/release/build/openssl-sys-e0f9d60d9223adb7/build-script-main`
[openssl-sys 0.9.80] cargo:rustc-cfg=const_fn
[openssl-sys 0.9.80] thread 'main' panicked at 'OpenSSL library directory does not exist: [""]', /usr/ports/www/leptos/work/leptos-0.1.0-alpha/cargo-crates/openssl-sys-0.9.80/build/main.rs:83:9
[openssl-sys 0.9.80] stack backtrace:
[openssl-sys 0.9.80] cargo:rustc-cfg=openssl
[openssl-sys 0.9.80] cargo:rerun-if-env-changed=X86_64_UNKNOWN_FREEBSD_OPENSSL_LIB_DIR
[openssl-sys 0.9.80] X86_64_UNKNOWN_FREEBSD_OPENSSL_LIB_DIR unset
[openssl-sys 0.9.80] cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
[openssl-sys 0.9.80] OPENSSL_LIB_DIR = 
[openssl-sys 0.9.80] cargo:rerun-if-env-changed=X86_64_UNKNOWN_FREEBSD_OPENSSL_INCLUDE_DIR
[openssl-sys 0.9.80] X86_64_UNKNOWN_FREEBSD_OPENSSL_INCLUDE_DIR unset
[openssl-sys 0.9.80] cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
[openssl-sys 0.9.80] OPENSSL_INCLUDE_DIR = 
[openssl-sys 0.9.80]    0: rust_begin_unwind
[openssl-sys 0.9.80]    1: core::panicking::panic_fmt
[openssl-sys 0.9.80]    2: build_script_main::main
[openssl-sys 0.9.80]    3: core::ops::function::FnOnce::call_once
[openssl-sys 0.9.80] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: failed to run custom build command for `openssl-sys v0.9.80`

Caused by:
  process didn't exit successfully: `/usr/ports/www/leptos/work/target/release/build/openssl-sys-e0f9d60d9223adb7/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rustc-cfg=openssl
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_FREEBSD_OPENSSL_LIB_DIR
  X86_64_UNKNOWN_FREEBSD_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR = 
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_FREEBSD_OPENSSL_INCLUDE_DIR
  X86_64_UNKNOWN_FREEBSD_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR = 

  --- stderr
  thread 'main' panicked at 'OpenSSL library directory does not exist: [""]', /usr/ports/www/leptos/work/leptos-0.1.0-alpha/cargo-crates/openssl-sys-0.9.80/build/main.rs:83:9
  stack backtrace:
     0: rust_begin_unwind
     1: core::panicking::panic_fmt
     2: build_script_main::main
     3: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
^C*** Signal 2=========>               ] 248/616: serde_json, ciborium                                                                                                                                 
```

**Comment by ChristopherBiscardi** [comment]
Assuming you copied some code from the examples, they use reqwest which depends on ring/openssl by default. You can switch to rustls for reqwest which avoids the issue.

```toml
reqwest = { version = "0.11.13", features = [
    "json",
    "rustls-tls",
], default-features = false }
```

**Comment by yurivict** [comment]
I found the problem - OPENSSL_LIB_DIR wasn't set.

Thanks for your help.

**Comment by tz182736** [comment]
can i get url to download open ssl ?

i did encounter same issue inside the example  hackernews and isomorphic counter.
