### ISSUE TITLE
Reactive system panicking at `already borrowed: BorrowMutError`

### ISSUE THREAD

**Issue by jquesada2016** [gbj/leptos#65]
I am working on a repro, but just wanted to raise the issue.

Here is a backtrace:

```rust
panicked at 'already borrowed: BorrowMutError', C:\Users\jose2\.cargo\git\checkouts\leptos-852582868f14a87e\21d7346\leptos_reactive\src\signal.rs:726:32

Stack:

Error
    at http://localhost:5173/src/wasm/wasm.js:428:21
    at logError (http://localhost:5173/src/wasm/wasm.js:237:18)
    at imports.wbg.__wbg_new_abda76e883ba8a5f (http://localhost:5173/src/wasm/wasm.js:427:66)
    at console_error_panic_hook::Error::new::hca9359d70b7a65b0 (http://localhost:5173/src/wasm/wasm_bg.wasm:wasm-function[7886]:0x2525df)
    at console_error_panic_hook::hook_impl::hd6342f4a1d3ee1fa (http://localhost:5173/src/wasm/wasm_bg.wasm:wasm-function[1491]:0x151490)
    at console_error_panic_hook::hook::h5583c33e69aaa70c (http://localhost:5173/src/wasm/wasm_bg.wasm:wasm-function[8484]:0x25aaca)
    at core::ops::function::Fn::call::h4709acb035a3f1ae (http://localhost:5173/src/wasm/wasm_bg.wasm:wasm-function[7565]:0x24d60d)
    at std::panicking::rust_panic_with_hook::h3534cfedda92faa6 (http://localhost:5173/src/wasm/wasm_bg.wasm:wasm-function[3320]:0x1d0181)
    at std::panicking::begin_panic_handler::{{closure}}::h0b26f08fa80310e7 (http://localhost:5173/src/wasm/wasm_bg.wasm:wasm-function[4244]:0x1fa6ba)
    at std::sys_common::backtrace::__rust_end_short_backtrace::hbf7b83761deb4f3e (http://localhost:5173/src/wasm/wasm_bg.wasm:wasm-function[9085]:0x2624d1)

Uncaught (in promise) RuntimeError: unreachable
    at __rust_start_panic (wasm_bg.wasm:0x26966c)
    at rust_panic (wasm_bg.wasm:0x264e18)
    at std::panicking::rust_panic_with_hook::h3534cfedda92faa6 (wasm_bg.wasm:0x1d01ac)
    at std::panicking::begin_panic_handler::{{closure}}::h0b26f08fa80310e7 (wasm_bg.wasm:0x1fa6ba)
    at std::sys_common::backtrace::__rust_end_short_backtrace::hbf7b83761deb4f3e (wasm_bg.wasm:0x2624d1)
    at rust_begin_unwind (wasm_bg.wasm:0x23a916)
    at core::panicking::panic_fmt::h855c11889f2fb721 (wasm_bg.wasm:0x25989d)
    at core::result::unwrap_failed::ha83ac9268ec678d9 (wasm_bg.wasm:0x212ae5)
    at core::cell::RefCell<T>::borrow_mut::h38eb0755cd71904b (wasm_bg.wasm:0x198361)
    at leptos_reactive::signal::SignalId::update::h68bb1fd62dd948e3 (wasm_bg.wasm:0x3a8e7)
```

**Comment by jquesada2016** [comment]
Hee it is @gbj 

```rust
use leptos::*;
use leptos_router::*;
use wasm_bindgen::prelude::*;

#[wasm_bindgen(start)]
pub fn start() {
  console_error_panic_hook::set_once();

  mount_to_body(view_fn);
}

fn view_fn(cx: Scope) -> impl Mountable {
  provide_context(cx, RouterIntegrationContext::new(BrowserIntegration {}));

  view! { cx,
    <span>
      <Router>
        <span>  // <-- won't compile whithout these
          <Routes>
            <Route path="/" element=|cx| view! { cx, <Home /> } />
            <Route path="/found-another" element=|cx| view! { cx, <h1>"bug!"</h1> } />
          </Routes>
        </span> // <-- won't compile whithout these
      </Router>
    </span>
  }
}

#[component]
fn Home(cx: Scope) -> Element {
  use_navigate(cx)("/found-another", Default::default()).unwrap();

  view! { cx,
    <h1>"/"</h1>
  }
}
```

**Comment by gbj** [comment]
Thanks. To be clear, if you remove that uae_navigate does it still panic?

**Comment by jquesada2016** [comment]
The workaround I am currently using is to just schedule the navigation in the next microtask using `wasm_bindgen_futures::spawn_local`, which runs after whatever was borrowed releases the lock.

**Comment by jquesada2016** [comment]
The `use_navigate()` does not panic, but calling the `fn` it returns does.

**Comment by gbj** [comment]
Thanks. This is the kind of thing the reactive system doesn't like: rendering the app requires reactively *reading* the current route, which synchronously renders the component, which *updates* the current route... such that you're mutating the value of the route signal within an effect that depends on the route signal.

I've basically moved your solution into the library, here, using `queue_microtask` rather than `spawn_local` for any navigation.

**Comment by jquesada2016** [comment]
Is this something that should potentially have a disclaimer for authors creating primitive utilities using `leptos_reactive`? Or is this a situation that the average user might find themselves in while using signals and effects?

I personally ran into it out of trying to create a `Redirect` component which redirects the user elsewhere if the component renders, which currently does not exist in the `leptos_router` crate. All other uses of signals and effects I've used haven't triggered this panic yet.

**Comment by gbj** [comment]
Yeah you know it's actually going to take a more general solution: I actually ran into the same thing in the TodoMVC example this morning. It's pretty easy to accidentally create these loops. I'll try to solve it without the user land/library land hack.

**Comment by nguiard** [comment]
Hi, I just ran into this today, on 0.3.1. Is it supposed to be fixed or is a solution still in the works?

**Comment by gbj** [comment]
@nguiard The reactive system has been almost completely rewritten since this issue. I'm quite sure the panic in your case was caused by something completely different from this old issue. Could you please open a new issue with a reproduction? Otherwise it won't be possible to help you.

**Comment by nguiard** [comment]
I wasn't specific enough, my bad. You are correct, the issue was caused by something completely different. I'll open an issue to describe it a bit and try to make a minimal reproduction. Thanks.
